<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/10/25 00:51:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=orangehrm_mysql',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
